version: '3'

services:
  shortener:
    image: synoskov/shortener
    restart: on-failure
    ports:
      - "8011:8080"
    env_file:
      - .env

  db:
    image: postgres:15-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: